sudo: required
services:
- docker
branches:
  except:
  - "/^feature\\/.*$/"
  - "/^release\\/.*$/"
  - "/^support\\/.*$/"
  - "/^hotfix\\/.*$/"
env:
  global:
  - COMMIT: "${TRAVIS_COMMIT::8}"
  - DOCKER_REPO: gnkz/nginx1.12
  - CGO_ENABLED: 0
  - GOOS: linux
  - GOARCH: amd64
  - secure: R8NEsMsrB9R45gjKJRoO82G2VI7OHBxZfXMNlUaixJc+fWAfoq5Tk6L2Gj6S35gGiPipMWvEQAJ06QhZXdki9W9jGNQemM7TM2ENp5tDkMM2ntwxERBPewUoFixMU8U6UmyJOAchMNOSDPAAR3jws5maE5OwRLQBB3zyEQCEdQXeTlCmDet8C4gxdyfsHPBxzaFGp1qyq1nEeZQLHO43uFNI8anuyiQS22/9J+z7sc68g5MwuT9nlMw0U61FjOX4TJ6RXdmn7DaKgshb2Hmt590KxK7CJxgNDi/DVUom5Q1ycektcc7abFkeQLEuCLUnxMo4EwNzMBDshpkPKJEwp2UK/VXlX2H8DNNKChqcZESIZNe0xSPDRWlxX3Eo8PqjEKLLhBZOzoKCtxHKP5SBVZHiXZJ5dC3tccPgT3Lxhx0EaWcTRQQGvtxT4f1mdfzyl2XWfowxjKcS50jLIEDrSrnI3S7vQU0K1jAR08rR3GTxcRUYTRvlc1ScGu0LC+S8TTBJxhe5gqxkELKorpKPW4I2gQrvb8x42o0YoMIaO/UcmYLpTvL5RdS/EWzk+Aik0Kzzv84DNHLjQMlMcmwvPiFWoQOTzIDUpN2jRMaWGhXJOhe+8shtI6jT1wgy33GiWGlCEK3vYnOHuz+Nq9rC8QX3UOP3S/U49aAW+SbNjGY=
install:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -t $DOCKER_REPO:$COMMIT -f Dockerfile .
script:
- docker run -d --name gnkz_nginx_test $DOCKER_REPO:$COMMIT
- docker ps | grep gnkz_nginx_test
after_success:
- if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "Skipping push"; exit 0; else echo
  "Pushing image to docker registry"; docker login -u gnkz -p $DOCKER_PASS; docker
  tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$TAG; docker push $DOCKER_REPO; fi;
notifications:
  hipchat:
    rooms:
      secure: v27Cqi7GhsIOFDC7ayUcC5i9J+vhj/ntKLwsppz5HEGQfJ0A/FKTh9tsemkFlLsm5juyTqEL/QsdyTfbe+gNICspxXsssECCTD1DORn5UvEj/AYFWCMwTsC+zmyUY3jeeTMThIMs97SXTmXYCeB22MeF0M8eMEH/sA+vZXXJYWNz0gMuRfyNT3oQtHzcyD6783O2VOuwBzJv7byGrmMBp+Mt0g697bZzh0ADitzi5W/8Oyps/hmQCvdiClXHhinP2bZLXDjEP5i101SJW5XmmwifiEGCA5J0E8AGMEeBhD46kWjruRXgR5gjy6NIwiQ0ri2VKQbSIbRxxnPzcNtsjgq/q/UoNnDY1c7kesZ2Fo2+oGfdL6MtdVYikcVNUUA52yPrdFditcIB/HQanBtiQbUeNbSn56PIuI53BJ31egA5oe9g3GSTDUQn+IchQKsRDjZvd0qwayZ2fY0gmbk6PareIzEpDuwzxSEYP3jn/ldgON+mjldxMCCRz6zYP9rG9fPtXp2dEds54mPewQPWpY3peSRh2CxbRMXDDsgP6O8WOno8eYylnKUDWL4KYKwO9opQjxhy2GKr6K10tvXwXE6/gxXFx4LX14EPy9iO7K02MexPAGw0No1k4+9IgCFapd95mASDQI08Yn5jpCYhLbai7gZJ71izDpgKhbs/f5k=
